### ISSUE TITLE
How do we create an Object stream from Observerble<T> ? 

### ISSUE THREAD

**Issue by jasperblues** [Jason3S/rx-stream#17]
Nice lib! 

How do we create an Object stream from Observerble<T> where T does not extend string or buffer?

**Comment by Jason3S** [comment]
Pull Request #19 addresses this.
Thank you for raising the issue.

**Comment by Jason3S** [comment]
This should be resolved with 3.2.1.

**Comment by jasperblues** [comment]
Great job, thank you!

**Comment by jasperblues** [comment]
Tested, but still receiving: `TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object`

**Comment by Jason3S** [comment]
It is necessary to pass in the stream options: 

``` typescript
rxToStream(src, { objectMode: true })
```

See: https://github.com/Jason3S/rx-stream#writing-objects-to-a-stream

**Comment by Jason3S** [comment]
It was added in Node 12: [Stream - writable.writableObjectMode | Node.js v13.11.0 Documentation](https://nodejs.org/api/stream.html#stream_writable_writableobjectmode)

```
writable.writableObjectMode
Added in: v12.3.0
<boolean>
Getter for the property objectMode of a given Writable stream.
```

**Comment by jasperblues** [comment]
```   
 asStream(options?: CursorStreamOptions<T>): Readable {
        this.logger.log(`Options: ${options}`);
        const records = this.result.records();
        return rxToStream(records, <ObjectReadableOptions> {objectMode: true});
    }
```
^-- Tried this and it produced the error. The records are `Observable<Record>`. I looked at test cases and they appear to use strings, even for object mode tests.

**Comment by Jason3S** [comment]
The error might be occurring at another location in your stream.

[rx-stream/end-to-end.test.ts](https://github.com/Jason3S/rx-stream/blob/master/src/end-to-end.test.ts) is an example. If the `{ objectMode: true }` is removed, it will give the same error you are seeing.

**Comment by jasperblues** [comment]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object

    at validChunk (_stream_writable.js:263:10)
    at WriteStream.Writable.write (_stream_writable.js:297:21)
    at ReadableObservableStream.ondata (_stream_readable.js:710:20)
    at ReadableObservableStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ReadableObservableStream.Readable.push (_stream_readable.js:224:10)
    at Object.next (/Users/jblues/driver/drivine/node_modules/rxjs-stream/dist/rxToStream.js:37:46)
```

Hmm, I don't think so. There's no pipeline here. I will look into it, and if I still think there's a bug, share the repository. (It is an open source project).

**Comment by Jason3S** [comment]
Please let me know what you find out.
